-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity getALUfunc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    instr : IN STD_LOGIC_VECTOR (5 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of getALUfunc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv6_D : STD_LOGIC_VECTOR (5 downto 0) := "001101";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_1A : STD_LOGIC_VECTOR (5 downto 0) := "011010";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv6_6 : STD_LOGIC_VECTOR (5 downto 0) := "000110";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_9 : STD_LOGIC_VECTOR (5 downto 0) := "001001";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_2D : STD_LOGIC_VECTOR (5 downto 0) := "101101";
    constant ap_const_lv6_3E : STD_LOGIC_VECTOR (5 downto 0) := "111110";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv6_11 : STD_LOGIC_VECTOR (5 downto 0) := "010001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_s_fu_549_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_32_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp4_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp7_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp1_fu_471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp2_fu_493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp3_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp5_fu_537_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal UnifiedRetVal_reg_98 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal tmp_13_fu_149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal instr_off_fu_305_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_38_fu_311_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_40_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_fu_351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_46_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal instr_off1_fu_411_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_53_fu_417_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal instr_off2_fu_433_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_54_fu_439_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal instr_off3_fu_455_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_55_fu_461_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal instr_off4_fu_477_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_56_fu_483_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal instr_off5_fu_499_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_57_fu_505_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal instr_off6_fu_521_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_58_fu_527_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_condition_60 : BOOLEAN;
    signal ap_condition_68 : BOOLEAN;
    signal ap_condition_76 : BOOLEAN;
    signal ap_condition_85 : BOOLEAN;
    signal ap_condition_95 : BOOLEAN;
    signal ap_condition_106 : BOOLEAN;
    signal ap_condition_118 : BOOLEAN;
    signal ap_condition_131 : BOOLEAN;
    signal ap_condition_144 : BOOLEAN;
    signal ap_condition_151 : BOOLEAN;


begin




    UnifiedRetVal_reg_98_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            UnifiedRetVal_reg_98 <= ap_const_lv4_0;
        elsif (ap_clk'event and ap_clk =  '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((ap_const_boolean_1 = ap_condition_151)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_6;
                elsif ((ap_const_boolean_1 = ap_condition_144)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_5;
                elsif (((tmp_37_fu_299_p2 = ap_const_lv1_1) and (tmp_32_fu_269_p2 = ap_const_lv1_0))) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_9;
                elsif ((tmp_32_fu_269_p2 = ap_const_lv1_1)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_0;
                elsif ((ap_const_boolean_1 = ap_condition_131)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_A;
                elsif ((ap_const_boolean_1 = ap_condition_118)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_1;
                elsif ((ap_const_boolean_1 = ap_condition_106)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_3;
                elsif ((ap_const_boolean_1 = ap_condition_95)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_7;
                elsif ((ap_const_boolean_1 = ap_condition_85)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_8;
                elsif ((ap_const_boolean_1 = ap_condition_76)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_B;
                elsif ((ap_const_boolean_1 = ap_condition_68)) then 
                    UnifiedRetVal_reg_98 <= ap_const_lv4_4;
                elsif ((ap_const_boolean_1 = ap_condition_60)) then 
                    UnifiedRetVal_reg_98 <= p_s_fu_549_p3;
                end if;
            end if; 
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            ap_CS_fsm <= ap_ST_fsm_state1;
        elsif (ap_clk'event and ap_clk =  '1') then
            ap_CS_fsm <= ap_NS_fsm;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            ap_return_preg <= ap_const_lv4_0;
        elsif (ap_clk'event and ap_clk =  '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                ap_return_preg <= UnifiedRetVal_reg_98;
            end if; 
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_condition_106_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2, tmp_45_fu_363_p2, tmp_52_fu_405_p2, icmp4_fu_427_p2, icmp7_fu_449_p2, icmp1_fu_471_p2, icmp2_fu_493_p2)
    begin
                ap_condition_106 <= ((icmp2_fu_493_p2 = ap_const_lv1_1) and (icmp1_fu_471_p2 = ap_const_lv1_0) and (icmp7_fu_449_p2 = ap_const_lv1_0) and (icmp4_fu_427_p2 = ap_const_lv1_0) and (tmp_52_fu_405_p2 = ap_const_lv1_0) and (tmp_45_fu_363_p2 = ap_const_lv1_0) and (icmp_fu_321_p2 = ap_const_lv1_0) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_condition_118_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2, tmp_45_fu_363_p2, tmp_52_fu_405_p2, icmp4_fu_427_p2, icmp7_fu_449_p2, icmp1_fu_471_p2, icmp2_fu_493_p2, icmp3_fu_515_p2)
    begin
                ap_condition_118 <= ((icmp3_fu_515_p2 = ap_const_lv1_1) and (icmp2_fu_493_p2 = ap_const_lv1_0) and (icmp1_fu_471_p2 = ap_const_lv1_0) and (icmp7_fu_449_p2 = ap_const_lv1_0) and (icmp4_fu_427_p2 = ap_const_lv1_0) and (tmp_52_fu_405_p2 = ap_const_lv1_0) and (tmp_45_fu_363_p2 = ap_const_lv1_0) and (icmp_fu_321_p2 = ap_const_lv1_0) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_condition_131_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2, tmp_45_fu_363_p2, tmp_52_fu_405_p2, icmp4_fu_427_p2, icmp7_fu_449_p2, icmp1_fu_471_p2, icmp2_fu_493_p2, icmp3_fu_515_p2, icmp5_fu_537_p2)
    begin
                ap_condition_131 <= ((icmp5_fu_537_p2 = ap_const_lv1_1) and (icmp3_fu_515_p2 = ap_const_lv1_0) and (icmp2_fu_493_p2 = ap_const_lv1_0) and (icmp1_fu_471_p2 = ap_const_lv1_0) and (icmp7_fu_449_p2 = ap_const_lv1_0) and (icmp4_fu_427_p2 = ap_const_lv1_0) and (tmp_52_fu_405_p2 = ap_const_lv1_0) and (tmp_45_fu_363_p2 = ap_const_lv1_0) and (icmp_fu_321_p2 = ap_const_lv1_0) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_condition_144_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2, tmp_45_fu_363_p2)
    begin
                ap_condition_144 <= ((tmp_45_fu_363_p2 = ap_const_lv1_1) and (icmp_fu_321_p2 = ap_const_lv1_0) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_condition_151_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2, tmp_45_fu_363_p2, tmp_52_fu_405_p2)
    begin
                ap_condition_151 <= ((tmp_52_fu_405_p2 = ap_const_lv1_1) and (tmp_45_fu_363_p2 = ap_const_lv1_0) and (icmp_fu_321_p2 = ap_const_lv1_0) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_condition_60_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2, tmp_45_fu_363_p2, tmp_52_fu_405_p2, icmp4_fu_427_p2, icmp7_fu_449_p2, icmp1_fu_471_p2, icmp2_fu_493_p2, icmp3_fu_515_p2, icmp5_fu_537_p2)
    begin
                ap_condition_60 <= ((icmp5_fu_537_p2 = ap_const_lv1_0) and (icmp3_fu_515_p2 = ap_const_lv1_0) and (icmp2_fu_493_p2 = ap_const_lv1_0) and (icmp1_fu_471_p2 = ap_const_lv1_0) and (icmp7_fu_449_p2 = ap_const_lv1_0) and (icmp4_fu_427_p2 = ap_const_lv1_0) and (tmp_52_fu_405_p2 = ap_const_lv1_0) and (tmp_45_fu_363_p2 = ap_const_lv1_0) and (icmp_fu_321_p2 = ap_const_lv1_0) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_condition_68_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2)
    begin
                ap_condition_68 <= ((icmp_fu_321_p2 = ap_const_lv1_1) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_condition_76_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2, tmp_45_fu_363_p2, tmp_52_fu_405_p2, icmp4_fu_427_p2)
    begin
                ap_condition_76 <= ((icmp4_fu_427_p2 = ap_const_lv1_1) and (tmp_52_fu_405_p2 = ap_const_lv1_0) and (tmp_45_fu_363_p2 = ap_const_lv1_0) and (icmp_fu_321_p2 = ap_const_lv1_0) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_condition_85_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2, tmp_45_fu_363_p2, tmp_52_fu_405_p2, icmp4_fu_427_p2, icmp7_fu_449_p2)
    begin
                ap_condition_85 <= ((icmp7_fu_449_p2 = ap_const_lv1_1) and (icmp4_fu_427_p2 = ap_const_lv1_0) and (tmp_52_fu_405_p2 = ap_const_lv1_0) and (tmp_45_fu_363_p2 = ap_const_lv1_0) and (icmp_fu_321_p2 = ap_const_lv1_0) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_condition_95_assign_proc : process(tmp_32_fu_269_p2, tmp_37_fu_299_p2, icmp_fu_321_p2, tmp_45_fu_363_p2, tmp_52_fu_405_p2, icmp4_fu_427_p2, icmp7_fu_449_p2, icmp1_fu_471_p2)
    begin
                ap_condition_95 <= ((icmp1_fu_471_p2 = ap_const_lv1_1) and (icmp7_fu_449_p2 = ap_const_lv1_0) and (icmp4_fu_427_p2 = ap_const_lv1_0) and (tmp_52_fu_405_p2 = ap_const_lv1_0) and (tmp_45_fu_363_p2 = ap_const_lv1_0) and (icmp_fu_321_p2 = ap_const_lv1_0) and (tmp_37_fu_299_p2 = ap_const_lv1_0) and (tmp_32_fu_269_p2 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(UnifiedRetVal_reg_98, ap_return_preg, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_return <= UnifiedRetVal_reg_98;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    icmp1_fu_471_p2 <= "1" when (tmp_55_fu_461_p4 = ap_const_lv5_0) else "0";
    icmp2_fu_493_p2 <= "1" when (tmp_56_fu_483_p4 = ap_const_lv5_0) else "0";
    icmp3_fu_515_p2 <= "1" when (tmp_57_fu_505_p4 = ap_const_lv5_0) else "0";
    icmp4_fu_427_p2 <= "1" when (tmp_53_fu_417_p4 = ap_const_lv5_0) else "0";
    icmp5_fu_537_p2 <= "1" when (tmp_58_fu_527_p4 = ap_const_lv5_0) else "0";
    icmp7_fu_449_p2 <= "1" when (tmp_54_fu_439_p4 = ap_const_lv5_0) else "0";
    icmp_fu_321_p2 <= "1" when (tmp_38_fu_311_p4 = ap_const_lv5_0) else "0";
    instr_off1_fu_411_p2 <= std_logic_vector(unsigned(instr) + unsigned(ap_const_lv6_1C));
    instr_off2_fu_433_p2 <= std_logic_vector(unsigned(instr) + unsigned(ap_const_lv6_21));
    instr_off3_fu_455_p2 <= std_logic_vector(unsigned(instr) + unsigned(ap_const_lv6_23));
    instr_off4_fu_477_p2 <= std_logic_vector(unsigned(instr) + unsigned(ap_const_lv6_2D));
    instr_off5_fu_499_p2 <= std_logic_vector(unsigned(instr) + unsigned(ap_const_lv6_3E));
    instr_off6_fu_521_p2 <= std_logic_vector(unsigned(instr) + unsigned(ap_const_lv6_35));
    instr_off_fu_305_p2 <= std_logic_vector(unsigned(instr) + unsigned(ap_const_lv6_29));
    p_s_fu_549_p3 <= 
        ap_const_lv4_2 when (tmp_fu_543_p2(0) = '1') else 
        ap_const_lv4_A;
    tmp_12_fu_155_p2 <= "1" when (instr = ap_const_lv6_22) else "0";
    tmp_13_fu_149_p2 <= "1" when (instr = ap_const_lv6_16) else "0";
    tmp_14_fu_161_p2 <= (tmp_13_fu_149_p2 or tmp_12_fu_155_p2);
    tmp_15_fu_167_p2 <= "1" when (instr = ap_const_lv6_15) else "0";
    tmp_16_fu_173_p2 <= (tmp_15_fu_167_p2 or tmp_14_fu_161_p2);
    tmp_17_fu_179_p2 <= "1" when (instr = ap_const_lv6_12) else "0";
    tmp_18_fu_185_p2 <= (tmp_17_fu_179_p2 or tmp_16_fu_173_p2);
    tmp_19_fu_191_p2 <= "1" when (instr = ap_const_lv6_10) else "0";
    tmp_20_fu_197_p2 <= (tmp_19_fu_191_p2 or tmp_18_fu_185_p2);
    tmp_21_fu_203_p2 <= "1" when (instr = ap_const_lv6_F) else "0";
    tmp_22_fu_209_p2 <= (tmp_21_fu_203_p2 or tmp_20_fu_197_p2);
    tmp_23_fu_215_p2 <= "1" when (instr = ap_const_lv6_E) else "0";
    tmp_24_fu_221_p2 <= (tmp_23_fu_215_p2 or tmp_22_fu_209_p2);
    tmp_25_fu_227_p2 <= "1" when (instr = ap_const_lv6_D) else "0";
    tmp_26_fu_233_p2 <= (tmp_25_fu_227_p2 or tmp_24_fu_221_p2);
    tmp_27_fu_239_p2 <= "1" when (instr = ap_const_lv6_4) else "0";
    tmp_28_fu_245_p2 <= (tmp_27_fu_239_p2 or tmp_26_fu_233_p2);
    tmp_29_fu_251_p2 <= "1" when (instr = ap_const_lv6_1) else "0";
    tmp_30_fu_257_p2 <= (tmp_29_fu_251_p2 or tmp_28_fu_245_p2);
    tmp_31_fu_263_p2 <= "1" when (instr = ap_const_lv6_0) else "0";
    tmp_32_fu_269_p2 <= (tmp_31_fu_263_p2 or tmp_30_fu_257_p2);
    tmp_33_fu_281_p2 <= "1" when (instr = ap_const_lv6_21) else "0";
    tmp_34_fu_275_p2 <= "1" when (instr = ap_const_lv6_A) else "0";
    tmp_35_fu_287_p2 <= (tmp_34_fu_275_p2 or tmp_33_fu_281_p2);
    tmp_36_fu_293_p2 <= "1" when (instr = ap_const_lv6_5) else "0";
    tmp_37_fu_299_p2 <= (tmp_36_fu_293_p2 or tmp_35_fu_287_p2);
    tmp_38_fu_311_p4 <= instr_off_fu_305_p2(5 downto 1);
    tmp_39_fu_333_p2 <= "1" when (instr = ap_const_lv6_1A) else "0";
    tmp_40_fu_327_p2 <= "1" when (instr = ap_const_lv6_19) else "0";
    tmp_41_fu_339_p2 <= (tmp_40_fu_327_p2 or tmp_39_fu_333_p2);
    tmp_42_fu_345_p2 <= "1" when (instr = ap_const_lv6_8) else "0";
    tmp_43_fu_351_p2 <= (tmp_42_fu_345_p2 or tmp_41_fu_339_p2);
    tmp_44_fu_357_p2 <= "1" when (instr = ap_const_lv6_6) else "0";
    tmp_45_fu_363_p2 <= (tmp_44_fu_357_p2 or tmp_43_fu_351_p2);
    tmp_46_fu_375_p2 <= "1" when (instr = ap_const_lv6_1C) else "0";
    tmp_47_fu_369_p2 <= "1" when (instr = ap_const_lv6_1B) else "0";
    tmp_48_fu_381_p2 <= (tmp_47_fu_369_p2 or tmp_46_fu_375_p2);
    tmp_49_fu_387_p2 <= "1" when (instr = ap_const_lv6_9) else "0";
    tmp_50_fu_393_p2 <= (tmp_49_fu_387_p2 or tmp_48_fu_381_p2);
    tmp_51_fu_399_p2 <= "1" when (instr = ap_const_lv6_7) else "0";
    tmp_52_fu_405_p2 <= (tmp_51_fu_399_p2 or tmp_50_fu_393_p2);
    tmp_53_fu_417_p4 <= instr_off1_fu_411_p2(5 downto 1);
    tmp_54_fu_439_p4 <= instr_off2_fu_433_p2(5 downto 1);
    tmp_55_fu_461_p4 <= instr_off3_fu_455_p2(5 downto 1);
    tmp_56_fu_483_p4 <= instr_off4_fu_477_p2(5 downto 1);
    tmp_57_fu_505_p4 <= instr_off5_fu_499_p2(5 downto 1);
    tmp_58_fu_527_p4 <= instr_off6_fu_521_p2(5 downto 1);
    tmp_fu_543_p2 <= "1" when (instr = ap_const_lv6_11) else "0";
end behav;
