-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity getALUresult is
port (
    ap_ready : OUT STD_LOGIC;
    aluFunction : IN STD_LOGIC_VECTOR (3 downto 0);
    operand1_V : IN STD_LOGIC_VECTOR (31 downto 0);
    operand2_V : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of getALUresult is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal add_ln209_fu_249_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_agg_result_V_0_phi_fu_55_p22 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln70_fu_79_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln214_fu_242_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln72_fu_85_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_235_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln74_fu_91_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_1_fu_228_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln76_fu_97_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_2_fu_221_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln78_fu_103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_192_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln80_fu_109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_fu_115_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_fu_121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_2_fu_177_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln90_fu_127_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_3_fu_162_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln92_fu_133_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln81_fu_216_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln85_fu_205_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln95_fu_145_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln94_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln556_1_fu_154_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln556_1_fu_158_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_s_fu_169_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln68_fu_173_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln556_fu_184_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln556_fu_188_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln887_1_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln887_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);


begin



    add_ln209_fu_249_p2 <= std_logic_vector(unsigned(operand2_V) + unsigned(operand1_V));

    ap_phi_mux_agg_result_V_0_phi_fu_55_p22_assign_proc : process(add_ln209_fu_249_p2, icmp_ln70_fu_79_p2, sub_ln214_fu_242_p2, icmp_ln72_fu_85_p2, ret_V_fu_235_p2, icmp_ln74_fu_91_p2, ret_V_1_fu_228_p2, icmp_ln76_fu_97_p2, ret_V_2_fu_221_p2, icmp_ln78_fu_103_p2, r_V_fu_192_p2, icmp_ln80_fu_109_p2, icmp_ln84_fu_115_p2, icmp_ln88_fu_121_p2, r_V_2_fu_177_p2, icmp_ln90_fu_127_p2, r_V_3_fu_162_p2, icmp_ln92_fu_133_p2, zext_ln81_fu_216_p1, zext_ln85_fu_205_p1, select_ln95_fu_145_p3)
    begin
        if (((icmp_ln92_fu_133_p2 = ap_const_lv1_0) and (icmp_ln90_fu_127_p2 = ap_const_lv1_0) and (icmp_ln88_fu_121_p2 = ap_const_lv1_0) and (icmp_ln84_fu_115_p2 = ap_const_lv1_0) and (icmp_ln80_fu_109_p2 = ap_const_lv1_0) and (icmp_ln78_fu_103_p2 = ap_const_lv1_0) and (icmp_ln76_fu_97_p2 = ap_const_lv1_0) and (icmp_ln74_fu_91_p2 = ap_const_lv1_0) and (icmp_ln72_fu_85_p2 = ap_const_lv1_0) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= select_ln95_fu_145_p3;
        elsif (((icmp_ln80_fu_109_p2 = ap_const_lv1_0) and (icmp_ln78_fu_103_p2 = ap_const_lv1_0) and (icmp_ln76_fu_97_p2 = ap_const_lv1_0) and (icmp_ln74_fu_91_p2 = ap_const_lv1_0) and (icmp_ln72_fu_85_p2 = ap_const_lv1_0) and (icmp_ln84_fu_115_p2 = ap_const_lv1_1) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= zext_ln85_fu_205_p1;
        elsif (((icmp_ln78_fu_103_p2 = ap_const_lv1_0) and (icmp_ln76_fu_97_p2 = ap_const_lv1_0) and (icmp_ln74_fu_91_p2 = ap_const_lv1_0) and (icmp_ln72_fu_85_p2 = ap_const_lv1_0) and (icmp_ln80_fu_109_p2 = ap_const_lv1_1) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= zext_ln81_fu_216_p1;
        elsif (((icmp_ln90_fu_127_p2 = ap_const_lv1_0) and (icmp_ln88_fu_121_p2 = ap_const_lv1_0) and (icmp_ln84_fu_115_p2 = ap_const_lv1_0) and (icmp_ln80_fu_109_p2 = ap_const_lv1_0) and (icmp_ln78_fu_103_p2 = ap_const_lv1_0) and (icmp_ln76_fu_97_p2 = ap_const_lv1_0) and (icmp_ln74_fu_91_p2 = ap_const_lv1_0) and (icmp_ln72_fu_85_p2 = ap_const_lv1_0) and (icmp_ln92_fu_133_p2 = ap_const_lv1_1) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= r_V_3_fu_162_p2;
        elsif (((icmp_ln88_fu_121_p2 = ap_const_lv1_0) and (icmp_ln84_fu_115_p2 = ap_const_lv1_0) and (icmp_ln80_fu_109_p2 = ap_const_lv1_0) and (icmp_ln78_fu_103_p2 = ap_const_lv1_0) and (icmp_ln76_fu_97_p2 = ap_const_lv1_0) and (icmp_ln74_fu_91_p2 = ap_const_lv1_0) and (icmp_ln72_fu_85_p2 = ap_const_lv1_0) and (icmp_ln90_fu_127_p2 = ap_const_lv1_1) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= r_V_2_fu_177_p2;
        elsif (((icmp_ln84_fu_115_p2 = ap_const_lv1_0) and (icmp_ln80_fu_109_p2 = ap_const_lv1_0) and (icmp_ln78_fu_103_p2 = ap_const_lv1_0) and (icmp_ln76_fu_97_p2 = ap_const_lv1_0) and (icmp_ln74_fu_91_p2 = ap_const_lv1_0) and (icmp_ln72_fu_85_p2 = ap_const_lv1_0) and (icmp_ln88_fu_121_p2 = ap_const_lv1_1) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= r_V_fu_192_p2;
        elsif (((icmp_ln76_fu_97_p2 = ap_const_lv1_0) and (icmp_ln74_fu_91_p2 = ap_const_lv1_0) and (icmp_ln72_fu_85_p2 = ap_const_lv1_0) and (icmp_ln78_fu_103_p2 = ap_const_lv1_1) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= ret_V_2_fu_221_p2;
        elsif (((icmp_ln74_fu_91_p2 = ap_const_lv1_0) and (icmp_ln72_fu_85_p2 = ap_const_lv1_0) and (icmp_ln76_fu_97_p2 = ap_const_lv1_1) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= ret_V_1_fu_228_p2;
        elsif (((icmp_ln72_fu_85_p2 = ap_const_lv1_0) and (icmp_ln74_fu_91_p2 = ap_const_lv1_1) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= ret_V_fu_235_p2;
        elsif (((icmp_ln72_fu_85_p2 = ap_const_lv1_1) and (icmp_ln70_fu_79_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= sub_ln214_fu_242_p2;
        elsif ((icmp_ln70_fu_79_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= add_ln209_fu_249_p2;
        else 
            ap_phi_mux_agg_result_V_0_phi_fu_55_p22 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return <= ap_phi_mux_agg_result_V_0_phi_fu_55_p22;
    icmp_ln70_fu_79_p2 <= "1" when (aluFunction = ap_const_lv4_0) else "0";
    icmp_ln72_fu_85_p2 <= "1" when (aluFunction = ap_const_lv4_9) else "0";
    icmp_ln74_fu_91_p2 <= "1" when (aluFunction = ap_const_lv4_1) else "0";
    icmp_ln76_fu_97_p2 <= "1" when (aluFunction = ap_const_lv4_3) else "0";
    icmp_ln78_fu_103_p2 <= "1" when (aluFunction = ap_const_lv4_B) else "0";
    icmp_ln80_fu_109_p2 <= "1" when (aluFunction = ap_const_lv4_5) else "0";
    icmp_ln84_fu_115_p2 <= "1" when (aluFunction = ap_const_lv4_6) else "0";
    icmp_ln887_1_fu_199_p2 <= "1" when (unsigned(operand1_V) < unsigned(operand2_V)) else "0";
    icmp_ln887_fu_210_p2 <= "1" when (signed(operand1_V) < signed(operand2_V)) else "0";
    icmp_ln88_fu_121_p2 <= "1" when (aluFunction = ap_const_lv4_4) else "0";
    icmp_ln90_fu_127_p2 <= "1" when (aluFunction = ap_const_lv4_7) else "0";
    icmp_ln92_fu_133_p2 <= "1" when (aluFunction = ap_const_lv4_8) else "0";
    icmp_ln94_fu_139_p2 <= "1" when (aluFunction = ap_const_lv4_2) else "0";
    p_Val2_s_fu_169_p1 <= operand2_V(5 - 1 downto 0);
    r_V_2_fu_177_p2 <= std_logic_vector(shift_right(signed(operand1_V),to_integer(unsigned('0' & zext_ln68_fu_173_p1(31-1 downto 0)))));
    r_V_3_fu_162_p2 <= std_logic_vector(shift_right(unsigned(operand1_V),to_integer(unsigned('0' & zext_ln556_1_fu_158_p1(31-1 downto 0)))));
    r_V_fu_192_p2 <= std_logic_vector(shift_left(unsigned(operand1_V),to_integer(unsigned('0' & zext_ln556_fu_188_p1(31-1 downto 0)))));
    ret_V_1_fu_228_p2 <= (operand2_V or operand1_V);
    ret_V_2_fu_221_p2 <= (operand2_V xor operand1_V);
    ret_V_fu_235_p2 <= (operand2_V and operand1_V);
    select_ln95_fu_145_p3 <= 
        operand1_V when (icmp_ln94_fu_139_p2(0) = '1') else 
        ap_const_lv32_0;
    sub_ln214_fu_242_p2 <= std_logic_vector(unsigned(operand1_V) - unsigned(operand2_V));
    trunc_ln556_1_fu_154_p1 <= operand2_V(5 - 1 downto 0);
    trunc_ln556_fu_184_p1 <= operand2_V(5 - 1 downto 0);
    zext_ln556_1_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln556_1_fu_154_p1),32));
    zext_ln556_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln556_fu_184_p1),32));
    zext_ln68_fu_173_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_s_fu_169_p1),32));
    zext_ln81_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln887_fu_210_p2),32));
    zext_ln85_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln887_1_fu_199_p2),32));
end behav;
