-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity getImmediate is
port (
    ap_ready : OUT STD_LOGIC;
    encodedInstr_V : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of getImmediate is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv7_23 : STD_LOGIC_VECTOR (6 downto 0) := "0100011";
    constant ap_const_lv20_FFFFF : STD_LOGIC_VECTOR (19 downto 0) := "11111111111111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_6F : STD_LOGIC_VECTOR (6 downto 0) := "1101111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv7_67 : STD_LOGIC_VECTOR (6 downto 0) := "1100111";
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_37 : STD_LOGIC_VECTOR (6 downto 0) := "0110111";
    constant ap_const_lv7_17 : STD_LOGIC_VECTOR (6 downto 0) := "0010111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal p_Result_2_fu_98_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_5_fu_86_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_6_fu_136_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_5_fu_126_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_7_fu_192_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_182_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_8_fu_172_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_234_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_Result_s_6_fu_270_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_262_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_fu_252_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_fu_90_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp4_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp23_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp26_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp29_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp30_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp5_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp28_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp31_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp35_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp36_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_73_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp37_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp41_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp40_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp42_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp7_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp6_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp43_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_76_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp8_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp44_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp48_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_77_fu_280_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp46_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp45_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_78_fu_294_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_74_fu_200_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp39_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp38_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_75_fu_214_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_152_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp34_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp33_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_162_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_118_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp27_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_108_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_fu_244_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_524_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal newSel1_fu_538_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond1_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel2_fu_552_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal newSel3_fu_566_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond3_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_fu_596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel5_fu_588_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal newSel6_fu_602_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond5_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel7_fu_616_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal newSel4_fu_580_p3 : STD_LOGIC_VECTOR (31 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        newSel7_fu_616_p3 when (or_cond6_fu_624_p2(0) = '1') else 
        newSel4_fu_580_p3;
    newSel1_fu_538_p3 <= 
        tmp_78_fu_294_p6 when (sel_tmp45_fu_500_p2(0) = '1') else 
        tmp_74_fu_200_p6;
    newSel2_fu_552_p3 <= 
        tmp_75_fu_214_p6 when (sel_tmp38_fu_440_p2(0) = '1') else 
        tmp_1_fu_152_p4;
    newSel3_fu_566_p3 <= 
        tmp_2_fu_162_p4 when (sel_tmp33_fu_410_p2(0) = '1') else 
        tmp_fu_118_p3;
    newSel4_fu_580_p3 <= 
        p_Result_s_fu_108_p1 when (sel_tmp6_fu_344_p2(0) = '1') else 
        r_V_fu_244_p3;
    newSel5_fu_588_p3 <= 
        newSel_fu_524_p3 when (or_cond_fu_532_p2(0) = '1') else 
        newSel1_fu_538_p3;
    newSel6_fu_602_p3 <= 
        newSel2_fu_552_p3 when (or_cond2_fu_560_p2(0) = '1') else 
        newSel3_fu_566_p3;
    newSel7_fu_616_p3 <= 
        newSel5_fu_588_p3 when (or_cond4_fu_596_p2(0) = '1') else 
        newSel6_fu_602_p3;
    newSel_fu_524_p3 <= 
        ap_const_lv32_0 when (sel_tmp48_fu_518_p2(0) = '1') else 
        tmp_77_fu_280_p6;
    or_cond1_fu_546_p2 <= (sel_tmp45_fu_500_p2 or sel_tmp39_fu_446_p2);
    or_cond2_fu_560_p2 <= (sel_tmp38_fu_440_p2 or sel_tmp34_fu_416_p2);
    or_cond3_fu_574_p2 <= (sel_tmp33_fu_410_p2 or sel_tmp27_fu_368_p2);
    or_cond4_fu_596_p2 <= (or_cond_fu_532_p2 or or_cond1_fu_546_p2);
    or_cond5_fu_610_p2 <= (or_cond3_fu_574_p2 or or_cond2_fu_560_p2);
    or_cond6_fu_624_p2 <= (or_cond5_fu_610_p2 or or_cond4_fu_596_p2);
    or_cond_fu_532_p2 <= (sel_tmp48_fu_518_p2 or sel_tmp46_fu_506_p2);
    p_Result_2_fu_98_p4 <= encodedInstr_V(31 downto 20);
    p_Result_4_fu_252_p4 <= encodedInstr_V(30 downto 21);
    p_Result_5_fu_126_p4 <= encodedInstr_V(11 downto 7);
    p_Result_6_fu_136_p4 <= encodedInstr_V(31 downto 25);
    p_Result_8_fu_172_p4 <= encodedInstr_V(11 downto 8);
    p_Result_9_fu_182_p4 <= encodedInstr_V(30 downto 25);
    p_Result_s_6_fu_270_p4 <= encodedInstr_V(19 downto 12);
    p_Result_s_fu_108_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_2_fu_98_p4),32));
    r_V_fu_244_p3 <= (tmp_3_fu_234_p4 & ap_const_lv12_0);
    sel_tmp18_fu_350_p2 <= (tmp_6_fu_90_p3 and sel_tmp5_fu_338_p2);
    sel_tmp1_fu_314_p2 <= "1" when (tmp_5_fu_86_p1 = ap_const_lv7_13) else "0";
    sel_tmp23_fu_356_p2 <= (sel_tmp5_fu_338_p2 xor ap_const_lv1_1);
    sel_tmp26_fu_362_p2 <= (sel_tmp23_fu_356_p2 and sel_tmp1_fu_314_p2);
    sel_tmp27_fu_368_p2 <= (sel_tmp26_fu_362_p2 or sel_tmp18_fu_350_p2);
    sel_tmp28_fu_374_p2 <= "0" when (tmp_5_fu_86_p1 = ap_const_lv7_67) else "1";
    sel_tmp29_fu_380_p2 <= "0" when (tmp_5_fu_86_p1 = ap_const_lv7_13) else "1";
    sel_tmp2_fu_320_p2 <= "1" when (tmp_5_fu_86_p1 = ap_const_lv7_3) else "0";
    sel_tmp30_fu_386_p2 <= "0" when (tmp_5_fu_86_p1 = ap_const_lv7_3) else "1";
    sel_tmp31_fu_398_p2 <= (tmp5_fu_392_p2 and sel_tmp28_fu_374_p2);
    sel_tmp32_fu_404_p2 <= (tmp_s_fu_112_p2 and sel_tmp31_fu_398_p2);
    sel_tmp33_fu_410_p2 <= (sel_tmp3_fu_326_p2 and sel_tmp32_fu_404_p2);
    sel_tmp34_fu_416_p2 <= (tmp_6_fu_90_p3 and sel_tmp32_fu_404_p2);
    sel_tmp35_fu_422_p2 <= (tmp_s_fu_112_p2 xor ap_const_lv1_1);
    sel_tmp36_fu_428_p2 <= (sel_tmp35_fu_422_p2 and sel_tmp31_fu_398_p2);
    sel_tmp37_fu_434_p2 <= (tmp_73_fu_146_p2 and sel_tmp36_fu_428_p2);
    sel_tmp38_fu_440_p2 <= (sel_tmp3_fu_326_p2 and sel_tmp37_fu_434_p2);
    sel_tmp39_fu_446_p2 <= (tmp_6_fu_90_p3 and sel_tmp37_fu_434_p2);
    sel_tmp3_fu_326_p2 <= (tmp_6_fu_90_p3 xor ap_const_lv1_1);
    sel_tmp40_fu_452_p2 <= (tmp_73_fu_146_p2 xor ap_const_lv1_1);
    sel_tmp41_fu_458_p2 <= "0" when (tmp_5_fu_86_p1 = ap_const_lv7_37) else "1";
    sel_tmp42_fu_464_p2 <= "0" when (tmp_5_fu_86_p1 = ap_const_lv7_17) else "1";
    sel_tmp43_fu_482_p2 <= (tmp7_fu_476_p2 and tmp6_fu_470_p2);
    sel_tmp44_fu_488_p2 <= (tmp_76_fu_228_p2 and sel_tmp43_fu_482_p2);
    sel_tmp45_fu_500_p2 <= (tmp8_fu_494_p2 and sel_tmp44_fu_488_p2);
    sel_tmp46_fu_506_p2 <= (tmp_6_fu_90_p3 and sel_tmp44_fu_488_p2);
    sel_tmp47_fu_512_p2 <= (tmp_76_fu_228_p2 xor ap_const_lv1_1);
    sel_tmp48_fu_518_p2 <= (sel_tmp47_fu_512_p2 and sel_tmp43_fu_482_p2);
    sel_tmp5_fu_338_p2 <= (tmp4_fu_332_p2 or sel_tmp_fu_308_p2);
    sel_tmp6_fu_344_p2 <= (sel_tmp5_fu_338_p2 and sel_tmp3_fu_326_p2);
    sel_tmp_fu_308_p2 <= "1" when (tmp_5_fu_86_p1 = ap_const_lv7_67) else "0";
    tmp4_fu_332_p2 <= (sel_tmp2_fu_320_p2 or sel_tmp1_fu_314_p2);
    tmp5_fu_392_p2 <= (sel_tmp30_fu_386_p2 and sel_tmp29_fu_380_p2);
    tmp6_fu_470_p2 <= (sel_tmp41_fu_458_p2 and sel_tmp40_fu_452_p2);
    tmp7_fu_476_p2 <= (sel_tmp42_fu_464_p2 and sel_tmp36_fu_428_p2);
    tmp8_fu_494_p2 <= (sel_tmp3_fu_326_p2 and sel_tmp31_fu_398_p2);
    tmp_1_fu_152_p4 <= ((ap_const_lv20_FFFFF & p_Result_6_fu_136_p4) & p_Result_5_fu_126_p4);
    tmp_2_fu_162_p4 <= ((ap_const_lv20_0 & p_Result_6_fu_136_p4) & p_Result_5_fu_126_p4);
    tmp_3_fu_234_p4 <= encodedInstr_V(31 downto 12);
    tmp_5_fu_86_p1 <= encodedInstr_V(7 - 1 downto 0);
    tmp_6_fu_90_p3 <= encodedInstr_V(31 downto 31);
    tmp_73_fu_146_p2 <= "1" when (tmp_5_fu_86_p1 = ap_const_lv7_63) else "0";
    tmp_74_fu_200_p6 <= ((((ap_const_lv20_FFFFF & tmp_7_fu_192_p3) & p_Result_9_fu_182_p4) & p_Result_8_fu_172_p4) & ap_const_lv1_0);
    tmp_75_fu_214_p6 <= ((((ap_const_lv20_0 & tmp_7_fu_192_p3) & p_Result_9_fu_182_p4) & p_Result_8_fu_172_p4) & ap_const_lv1_0);
    tmp_76_fu_228_p2 <= "1" when (tmp_5_fu_86_p1 = ap_const_lv7_6F) else "0";
    tmp_77_fu_280_p6 <= ((((ap_const_lv12_FFF & p_Result_s_6_fu_270_p4) & tmp_8_fu_262_p3) & p_Result_4_fu_252_p4) & ap_const_lv1_0);
    tmp_78_fu_294_p6 <= ((((ap_const_lv12_0 & p_Result_s_6_fu_270_p4) & tmp_8_fu_262_p3) & p_Result_4_fu_252_p4) & ap_const_lv1_0);
    tmp_7_fu_192_p3 <= encodedInstr_V(7 downto 7);
    tmp_8_fu_262_p3 <= encodedInstr_V(20 downto 20);
    tmp_fu_118_p3 <= (ap_const_lv20_FFFFF & p_Result_2_fu_98_p4);
    tmp_s_fu_112_p2 <= "1" when (tmp_5_fu_86_p1 = ap_const_lv7_23) else "0";
end behav;
