-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity getMemoryMask is
port (
    ap_ready : OUT STD_LOGIC;
    instr : IN STD_LOGIC_VECTOR (5 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of getMemoryMask is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv6_D : STD_LOGIC_VECTOR (5 downto 0) := "001101";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_s_fu_46_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_60_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_66_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_78_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_84_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp8_fu_90_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_72_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp9_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_96_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_40_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_fu_52_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp12_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp19_cast_fu_188_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp11_fu_138_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp20_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp21_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp22_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp24_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp23_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp25_fu_240_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp19_fu_202_p3 : STD_LOGIC_VECTOR (2 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        sel_tmp25_fu_240_p3 when (tmp_11_fu_248_p2(0) = '1') else 
        sel_tmp19_fu_202_p3;
    p_s_fu_52_p3 <= 
        ap_const_lv3_3 when (tmp_s_fu_46_p2(0) = '1') else 
        ap_const_lv3_5;
    sel_tmp10_fu_132_p2 <= (sel_tmp5_fu_126_p2 and sel_tmp4_fu_120_p2);
    sel_tmp11_fu_138_p3 <= 
        p_s_fu_52_p3 when (sel_tmp10_fu_132_p2(0) = '1') else 
        ap_const_lv3_4;
    sel_tmp12_fu_146_p2 <= "1" when (instr = ap_const_lv6_15) else "0";
    sel_tmp13_fu_152_p2 <= "1" when (instr = ap_const_lv6_D) else "0";
    sel_tmp14_fu_158_p2 <= (sel_tmp13_fu_152_p2 or sel_tmp12_fu_146_p2);
    sel_tmp15_fu_164_p2 <= "1" when (instr = ap_const_lv6_16) else "0";
    sel_tmp16_fu_170_p2 <= "1" when (instr = ap_const_lv6_F) else "0";
    sel_tmp17_fu_176_p2 <= (sel_tmp16_fu_170_p2 or sel_tmp15_fu_164_p2);
    sel_tmp18_fu_182_p2 <= (sel_tmp8_fu_72_p2 and sel_tmp17_fu_176_p2);
    sel_tmp19_cast_fu_188_p3 <= 
        ap_const_lv3_2 when (sel_tmp18_fu_182_p2(0) = '1') else 
        ap_const_lv3_0;
    sel_tmp19_fu_202_p3 <= 
        sel_tmp19_cast_fu_188_p3 when (tmp_10_fu_196_p2(0) = '1') else 
        sel_tmp11_fu_138_p3;
    sel_tmp1_fu_96_p2 <= (tmp8_fu_90_p2 and sel_tmp8_fu_72_p2);
    sel_tmp20_fu_210_p2 <= "1" when (instr = ap_const_lv6_22) else "0";
    sel_tmp21_fu_216_p2 <= "1" when (instr = ap_const_lv6_12) else "0";
    sel_tmp22_fu_222_p2 <= (sel_tmp21_fu_216_p2 or sel_tmp20_fu_210_p2);
    sel_tmp23_fu_228_p2 <= (sel_tmp22_fu_222_p2 and sel_tmp1_fu_96_p2);
    sel_tmp24_fu_234_p2 <= (tmp_fu_40_p2 and sel_tmp4_fu_120_p2);
    sel_tmp25_fu_240_p3 <= 
        ap_const_lv3_1 when (sel_tmp24_fu_234_p2(0) = '1') else 
        ap_const_lv3_4;
    sel_tmp2_fu_102_p2 <= "0" when (instr = ap_const_lv6_22) else "1";
    sel_tmp3_fu_108_p2 <= "0" when (instr = ap_const_lv6_12) else "1";
    sel_tmp4_fu_120_p2 <= (tmp9_fu_114_p2 and sel_tmp1_fu_96_p2);
    sel_tmp5_fu_126_p2 <= (tmp_fu_40_p2 xor ap_const_lv1_1);
    sel_tmp6_fu_60_p2 <= "0" when (instr = ap_const_lv6_15) else "1";
    sel_tmp7_fu_66_p2 <= "0" when (instr = ap_const_lv6_D) else "1";
    sel_tmp8_fu_72_p2 <= (sel_tmp7_fu_66_p2 and sel_tmp6_fu_60_p2);
    sel_tmp9_fu_78_p2 <= "0" when (instr = ap_const_lv6_16) else "1";
    sel_tmp_fu_84_p2 <= "0" when (instr = ap_const_lv6_F) else "1";
    tmp8_fu_90_p2 <= (sel_tmp_fu_84_p2 and sel_tmp9_fu_78_p2);
    tmp9_fu_114_p2 <= (sel_tmp3_fu_108_p2 and sel_tmp2_fu_102_p2);
    tmp_10_fu_196_p2 <= (sel_tmp18_fu_182_p2 or sel_tmp14_fu_158_p2);
    tmp_11_fu_248_p2 <= (sel_tmp24_fu_234_p2 or sel_tmp23_fu_228_p2);
    tmp_fu_40_p2 <= "1" when (instr = ap_const_lv6_E) else "0";
    tmp_s_fu_46_p2 <= "1" when (instr = ap_const_lv6_10) else "0";
end behav;
