-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity branchPCcalculation is
port (
    ap_ready : OUT STD_LOGIC;
    aluResult_V : IN STD_LOGIC_VECTOR (31 downto 0);
    encodedInstr_V : IN STD_LOGIC_VECTOR (31 downto 0);
    pcReg_V : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of branchPCcalculation is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv6_6 : STD_LOGIC_VECTOR (5 downto 0) := "000110";
    constant ap_const_lv6_9 : STD_LOGIC_VECTOR (5 downto 0) := "001001";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_getInstrType_fu_68_ap_ready : STD_LOGIC;
    signal tmp_getInstrType_fu_68_ap_return : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_getImmediate_fu_74_ap_ready : STD_LOGIC;
    signal grp_getImmediate_fu_74_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_p_06_pn_phi_fu_51_p14 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln22_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln24_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln28_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln30_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln32_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln22_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_44_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);

    component getInstrType IS
    port (
        ap_ready : OUT STD_LOGIC;
        encodedInstr_V : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component getImmediate IS
    port (
        ap_ready : OUT STD_LOGIC;
        encodedInstr_V : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    tmp_getInstrType_fu_68 : component getInstrType
    port map (
        ap_ready => tmp_getInstrType_fu_68_ap_ready,
        encodedInstr_V => encodedInstr_V,
        ap_return => tmp_getInstrType_fu_68_ap_return);

    grp_getImmediate_fu_74 : component getImmediate
    port map (
        ap_ready => grp_getImmediate_fu_74_ap_ready,
        encodedInstr_V => encodedInstr_V,
        ap_return => grp_getImmediate_fu_74_ap_return);




    and_ln22_fu_98_p2 <= (icmp_ln879_fu_92_p2 and icmp_ln22_fu_86_p2);
    and_ln26_fu_128_p2 <= (icmp_ln879_44_fu_122_p2 and icmp_ln26_fu_116_p2);
    and_ln28_fu_140_p2 <= (icmp_ln879_fu_92_p2 and icmp_ln28_fu_134_p2);
    and_ln30_fu_152_p2 <= (icmp_ln879_44_fu_122_p2 and icmp_ln30_fu_146_p2);
    and_ln32_fu_164_p2 <= (icmp_ln879_fu_92_p2 and icmp_ln32_fu_158_p2);

    ap_phi_mux_p_06_pn_phi_fu_51_p14_assign_proc : process(grp_getImmediate_fu_74_ap_return, and_ln22_fu_98_p2, or_ln24_fu_110_p2, and_ln26_fu_128_p2, and_ln28_fu_140_p2, and_ln30_fu_152_p2, and_ln32_fu_164_p2)
    begin
        if (((ap_const_lv1_0 = and_ln32_fu_164_p2) and (ap_const_lv1_0 = and_ln30_fu_152_p2) and (ap_const_lv1_0 = and_ln28_fu_140_p2) and (ap_const_lv1_0 = and_ln26_fu_128_p2) and (or_ln24_fu_110_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln22_fu_98_p2))) then 
            ap_phi_mux_p_06_pn_phi_fu_51_p14 <= ap_const_lv32_4;
        elsif (((ap_const_lv1_1 = and_ln22_fu_98_p2) or ((or_ln24_fu_110_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln22_fu_98_p2)) or ((ap_const_lv1_0 = and_ln30_fu_152_p2) and (ap_const_lv1_0 = and_ln28_fu_140_p2) and (ap_const_lv1_0 = and_ln26_fu_128_p2) and (ap_const_lv1_1 = and_ln32_fu_164_p2) and (or_ln24_fu_110_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln22_fu_98_p2)) or ((ap_const_lv1_0 = and_ln28_fu_140_p2) and (ap_const_lv1_0 = and_ln26_fu_128_p2) and (ap_const_lv1_1 = and_ln30_fu_152_p2) and (or_ln24_fu_110_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln22_fu_98_p2)) or ((ap_const_lv1_0 = and_ln26_fu_128_p2) and (ap_const_lv1_1 = and_ln28_fu_140_p2) and (or_ln24_fu_110_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln22_fu_98_p2)) or ((ap_const_lv1_1 = and_ln26_fu_128_p2) and (or_ln24_fu_110_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln22_fu_98_p2)))) then 
            ap_phi_mux_p_06_pn_phi_fu_51_p14 <= grp_getImmediate_fu_74_ap_return;
        else 
            ap_phi_mux_p_06_pn_phi_fu_51_p14 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(ap_phi_mux_p_06_pn_phi_fu_51_p14) + unsigned(pcReg_V));
    icmp_ln22_fu_86_p2 <= "1" when (tmp_getInstrType_fu_68_ap_return = ap_const_lv6_5) else "0";
    icmp_ln24_fu_104_p2 <= "0" when (tmp_getInstrType_fu_68_ap_return = ap_const_lv6_A) else "1";
    icmp_ln26_fu_116_p2 <= "1" when (tmp_getInstrType_fu_68_ap_return = ap_const_lv6_8) else "0";
    icmp_ln28_fu_134_p2 <= "1" when (tmp_getInstrType_fu_68_ap_return = ap_const_lv6_6) else "0";
    icmp_ln30_fu_146_p2 <= "1" when (tmp_getInstrType_fu_68_ap_return = ap_const_lv6_9) else "0";
    icmp_ln32_fu_158_p2 <= "1" when (tmp_getInstrType_fu_68_ap_return = ap_const_lv6_7) else "0";
    icmp_ln879_44_fu_122_p2 <= "1" when (aluResult_V = ap_const_lv32_1) else "0";
    icmp_ln879_fu_92_p2 <= "1" when (aluResult_V = ap_const_lv32_0) else "0";
    or_ln24_fu_110_p2 <= (icmp_ln879_fu_92_p2 or icmp_ln24_fu_104_p2);
end behav;
