-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity getImmediate is
port (
    ap_ready : OUT STD_LOGIC;
    encodedInstr_V : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of getImmediate is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv7_67 : STD_LOGIC_VECTOR (6 downto 0) := "1100111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv7_23 : STD_LOGIC_VECTOR (6 downto 0) := "0100011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv20_FFFFF : STD_LOGIC_VECTOR (19 downto 0) := "11111111111111111111";
    constant ap_const_lv7_6F : STD_LOGIC_VECTOR (6 downto 0) := "1101111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv7_37 : STD_LOGIC_VECTOR (6 downto 0) := "0110111";
    constant ap_const_lv7_17 : STD_LOGIC_VECTOR (6 downto 0) := "0010111";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal trunc_ln879_fu_88_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln879_39_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_40_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln132_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_122_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln132_1_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1503_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_142_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_162_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln1503_6_fu_172_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln_fu_182_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_15_fu_200_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_208_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_218_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln214_3_fu_228_p5 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_fu_264_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_2_fu_282_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_16_fu_292_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_300_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln132_1_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln134_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln134_1_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln132_2_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_1_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln134_2_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln134_1_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln134_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln134_2_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_41_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln879_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln879_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln879_1_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_42_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln879_2_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln144_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln879_1_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln144_1_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln144_1_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln144_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln144_2_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln879_43_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln879_3_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln879_2_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln879_4_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln214_8_fu_310_p5 : STD_LOGIC_VECTOR (19 downto 0);
    signal select_ln879_fu_504_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal and_ln1503_3_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1503_2_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln214_fu_190_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln214_1_fu_322_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln1503_1_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1_fu_244_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln214_1_fu_240_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln1503_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln879_3_fu_538_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sel_tmp7_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln132_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_1_fu_152_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_fu_274_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln879_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln879_fu_512_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln879_1_fu_522_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln879_2_fu_530_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln879_1_fu_546_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln879_2_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln879_3_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln879_5_fu_568_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln879_6_fu_582_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln879_4_fu_590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln879_5_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln879_7_fu_596_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln879_4_fu_560_p3 : STD_LOGIC_VECTOR (31 downto 0);


begin



    and_ln132_fu_136_p2 <= (xor_ln1503_fu_130_p2 and or_ln132_1_fu_116_p2);
    and_ln134_1_fu_390_p2 <= (icmp_ln134_fu_366_p2 and icmp_ln134_2_fu_378_p2);
    and_ln134_2_fu_396_p2 <= (and_ln134_fu_384_p2 and and_ln134_1_fu_390_p2);
    and_ln134_fu_384_p2 <= (or_ln132_2_fu_342_p2 and icmp_ln134_1_fu_372_p2);
    and_ln144_1_fu_462_p2 <= (icmp_ln144_1_fu_450_p2 and and_ln879_1_fu_420_p2);
    and_ln144_2_fu_468_p2 <= (and_ln144_fu_456_p2 and and_ln144_1_fu_462_p2);
    and_ln144_fu_456_p2 <= (xor_ln879_1_fu_438_p2 and icmp_ln144_fu_444_p2);
    and_ln1503_1_fu_432_p2 <= (tmp_13_fu_122_p3 and and_ln879_2_fu_426_p2);
    and_ln1503_2_fu_480_p2 <= (xor_ln1503_fu_130_p2 and and_ln879_fu_402_p2);
    and_ln1503_3_fu_486_p2 <= (xor_ln1503_fu_130_p2 and and_ln879_3_fu_474_p2);
    and_ln1503_fu_408_p2 <= (tmp_13_fu_122_p3 and and_ln879_fu_402_p2);
    and_ln879_1_fu_420_p2 <= (xor_ln879_fu_414_p2 and and_ln134_2_fu_396_p2);
    and_ln879_2_fu_426_p2 <= (icmp_ln879_42_fu_194_p2 and and_ln879_1_fu_420_p2);
    and_ln879_3_fu_474_p2 <= (icmp_ln879_43_fu_258_p2 and and_ln144_2_fu_468_p2);
    and_ln879_4_fu_498_p2 <= (xor_ln879_2_fu_492_p2 and and_ln144_2_fu_468_p2);
    and_ln879_fu_402_p2 <= (icmp_ln879_41_fu_156_p2 and and_ln134_2_fu_396_p2);
    ap_ready <= ap_const_logic_1;
    ap_return <= 
        select_ln879_7_fu_596_p3 when (or_ln879_5_fu_604_p2(0) = '1') else 
        select_ln879_4_fu_560_p3;
    icmp_ln134_1_fu_372_p2 <= "0" when (trunc_ln879_fu_88_p1 = ap_const_lv7_13) else "1";
    icmp_ln134_2_fu_378_p2 <= "0" when (trunc_ln879_fu_88_p1 = ap_const_lv7_3) else "1";
    icmp_ln134_fu_366_p2 <= "0" when (trunc_ln879_fu_88_p1 = ap_const_lv7_67) else "1";
    icmp_ln144_1_fu_450_p2 <= "0" when (trunc_ln879_fu_88_p1 = ap_const_lv7_17) else "1";
    icmp_ln144_fu_444_p2 <= "0" when (trunc_ln879_fu_88_p1 = ap_const_lv7_37) else "1";
    icmp_ln879_39_fu_98_p2 <= "1" when (trunc_ln879_fu_88_p1 = ap_const_lv7_3) else "0";
    icmp_ln879_40_fu_104_p2 <= "1" when (trunc_ln879_fu_88_p1 = ap_const_lv7_67) else "0";
    icmp_ln879_41_fu_156_p2 <= "1" when (trunc_ln879_fu_88_p1 = ap_const_lv7_23) else "0";
    icmp_ln879_42_fu_194_p2 <= "1" when (trunc_ln879_fu_88_p1 = ap_const_lv7_63) else "0";
    icmp_ln879_43_fu_258_p2 <= "1" when (trunc_ln879_fu_88_p1 = ap_const_lv7_6F) else "0";
    icmp_ln879_fu_92_p2 <= "1" when (trunc_ln879_fu_88_p1 = ap_const_lv7_13) else "0";
    or_ln132_1_fu_116_p2 <= (or_ln132_fu_110_p2 or icmp_ln879_fu_92_p2);
    or_ln132_2_fu_342_p2 <= (xor_ln132_1_fu_336_p2 or tmp_13_fu_122_p3);
    or_ln132_fu_110_p2 <= (icmp_ln879_40_fu_104_p2 or icmp_ln879_39_fu_98_p2);
    or_ln134_1_fu_354_p2 <= (or_ln134_fu_348_p2 or icmp_ln879_40_fu_104_p2);
    or_ln134_fu_348_p2 <= (icmp_ln879_fu_92_p2 or icmp_ln879_39_fu_98_p2);
    or_ln1_fu_244_p6 <= ((((ap_const_lv20_FFFFF & tmp_15_fu_200_p3) & tmp_9_fu_208_p4) & tmp_s_fu_218_p4) & ap_const_lv1_0);
    or_ln214_1_fu_322_p6 <= ((((ap_const_lv12_FFF & tmp_2_fu_282_p4) & tmp_16_fu_292_p3) & tmp_3_fu_300_p4) & ap_const_lv1_0);
    or_ln214_3_fu_228_p5 <= (((tmp_15_fu_200_p3 & tmp_9_fu_208_p4) & tmp_s_fu_218_p4) & ap_const_lv1_0);
    or_ln214_8_fu_310_p5 <= (((tmp_2_fu_282_p4 & tmp_16_fu_292_p3) & tmp_3_fu_300_p4) & ap_const_lv1_0);
    or_ln879_1_fu_546_p3 <= (ap_const_lv20_FFFFF & select_ln879_3_fu_538_p3);
    or_ln879_2_fu_554_p2 <= (sel_tmp7_fu_360_p2 or and_ln1503_fu_408_p2);
    or_ln879_3_fu_576_p2 <= (and_ln1503_2_fu_480_p2 or and_ln144_2_fu_468_p2);
    or_ln879_4_fu_590_p2 <= (or_ln879_2_fu_554_p2 or and_ln879_2_fu_426_p2);
    or_ln879_5_fu_604_p2 <= (or_ln879_4_fu_590_p2 or or_ln879_3_fu_576_p2);
    or_ln879_fu_516_p2 <= (and_ln879_4_fu_498_p2 or and_ln1503_3_fu_486_p2);
    or_ln_fu_182_p3 <= (tmp_fu_162_p4 & trunc_ln1503_6_fu_172_p4);
    r_V_1_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_fu_142_p4),32));
    r_V_fu_142_p4 <= encodedInstr_V(31 downto 20);
    ret_V_fu_274_p3 <= (tmp_1_fu_264_p4 & ap_const_lv12_0);
    sel_tmp7_fu_360_p2 <= (or_ln134_1_fu_354_p2 and or_ln132_2_fu_342_p2);
    select_ln879_1_fu_522_p3 <= 
        zext_ln214_fu_190_p1 when (and_ln1503_2_fu_480_p2(0) = '1') else 
        or_ln214_1_fu_322_p6;
    select_ln879_2_fu_530_p3 <= 
        or_ln1_fu_244_p6 when (and_ln1503_1_fu_432_p2(0) = '1') else 
        zext_ln214_1_fu_240_p1;
    select_ln879_3_fu_538_p3 <= 
        or_ln_fu_182_p3 when (and_ln1503_fu_408_p2(0) = '1') else 
        r_V_fu_142_p4;
    select_ln879_4_fu_560_p3 <= 
        r_V_1_fu_152_p1 when (and_ln132_fu_136_p2(0) = '1') else 
        ret_V_fu_274_p3;
    select_ln879_5_fu_568_p3 <= 
        zext_ln879_fu_512_p1 when (or_ln879_fu_516_p2(0) = '1') else 
        select_ln879_1_fu_522_p3;
    select_ln879_6_fu_582_p3 <= 
        select_ln879_2_fu_530_p3 when (and_ln879_2_fu_426_p2(0) = '1') else 
        or_ln879_1_fu_546_p3;
    select_ln879_7_fu_596_p3 <= 
        select_ln879_5_fu_568_p3 when (or_ln879_3_fu_576_p2(0) = '1') else 
        select_ln879_6_fu_582_p3;
    select_ln879_fu_504_p3 <= 
        ap_const_lv20_0 when (and_ln879_4_fu_498_p2(0) = '1') else 
        or_ln214_8_fu_310_p5;
    tmp_13_fu_122_p3 <= encodedInstr_V(31 downto 31);
    tmp_15_fu_200_p3 <= encodedInstr_V(7 downto 7);
    tmp_16_fu_292_p3 <= encodedInstr_V(20 downto 20);
    tmp_1_fu_264_p4 <= encodedInstr_V(31 downto 12);
    tmp_2_fu_282_p4 <= encodedInstr_V(19 downto 12);
    tmp_3_fu_300_p4 <= encodedInstr_V(30 downto 21);
    tmp_9_fu_208_p4 <= encodedInstr_V(30 downto 25);
    tmp_fu_162_p4 <= encodedInstr_V(31 downto 25);
    tmp_s_fu_218_p4 <= encodedInstr_V(11 downto 8);
    trunc_ln1503_6_fu_172_p4 <= encodedInstr_V(11 downto 7);
    trunc_ln879_fu_88_p1 <= encodedInstr_V(7 - 1 downto 0);
    xor_ln132_1_fu_336_p2 <= (or_ln132_1_fu_116_p2 xor ap_const_lv1_1);
    xor_ln1503_fu_130_p2 <= (tmp_13_fu_122_p3 xor ap_const_lv1_1);
    xor_ln879_1_fu_438_p2 <= (icmp_ln879_42_fu_194_p2 xor ap_const_lv1_1);
    xor_ln879_2_fu_492_p2 <= (icmp_ln879_43_fu_258_p2 xor ap_const_lv1_1);
    xor_ln879_fu_414_p2 <= (icmp_ln879_41_fu_156_p2 xor ap_const_lv1_1);
    zext_ln214_1_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln214_3_fu_228_p5),32));
    zext_ln214_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_182_p3),32));
    zext_ln879_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln879_fu_504_p3),32));
end behav;
