-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Framer_operations is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    data_word_sig_markerAlignment_V : IN STD_LOGIC_VECTOR (31 downto 0);
    oof_sig : OUT STD_LOGIC;
    frame_pulse_sig : OUT STD_LOGIC;
    out_nextphase : OUT STD_LOGIC_VECTOR (2 downto 0);
    out_frm_cnt_V : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_align_V : OUT STD_LOGIC_VECTOR (31 downto 0);
    frame_pulse_notify : OUT STD_LOGIC;
    active_operation : IN STD_LOGIC_VECTOR (4 downto 0) );
end;


architecture behav of Framer_operations is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Framer_operations,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2104-2-i,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.042042,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=71,HLS_SYN_LUT=1002,HLS_VERSION=2018_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal frm_cnt_reg_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    signal oof_sig_reg : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal frame_pulse_sig_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal nextphase_reg : STD_LOGIC_VECTOR (2 downto 0) := "011";
    signal align_reg_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal frame_pulse_notify_r : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal r_V_39_fu_350_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal active_operation_rea_read_fu_138_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal r_V_37_fu_422_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_35_fu_494_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_33_fu_566_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_31_fu_638_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_29_fu_710_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_27_fu_782_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_25_fu_854_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_23_fu_926_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_21_fu_998_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_19_fu_1070_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_17_fu_1142_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_15_fu_1214_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_13_fu_1286_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_11_fu_1358_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_9_fu_1430_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_7_fu_1502_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_5_fu_1574_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_3_fu_1646_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_1_fu_1718_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_114_fu_288_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_38_fu_292_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_116_fu_306_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_117_fu_318_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_118_fu_322_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t19_fu_328_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_115_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t19_fu_336_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f19_fu_310_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_342_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_109_fu_360_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_36_fu_364_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_111_fu_378_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_112_fu_390_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_113_fu_394_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t18_fu_400_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_110_fu_370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t18_fu_408_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f18_fu_382_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_fu_414_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_104_fu_432_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_34_fu_436_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_106_fu_450_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_107_fu_462_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_108_fu_466_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t17_fu_472_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_105_fu_442_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t17_fu_480_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f17_fu_454_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_17_fu_486_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_99_fu_504_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_32_fu_508_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_101_fu_522_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_102_fu_534_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_103_fu_538_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t16_fu_544_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_100_fu_514_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t16_fu_552_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f16_fu_526_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_16_fu_558_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_94_fu_576_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_30_fu_580_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_96_fu_594_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_97_fu_606_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_98_fu_610_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t15_fu_616_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_95_fu_586_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t15_fu_624_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f15_fu_598_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_630_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_89_fu_648_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_28_fu_652_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_91_fu_666_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_92_fu_678_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_93_fu_682_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t14_fu_688_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_90_fu_658_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t14_fu_696_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f14_fu_670_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_702_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_84_fu_720_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_26_fu_724_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_86_fu_738_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_87_fu_750_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_88_fu_754_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t13_fu_760_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_85_fu_730_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t13_fu_768_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f13_fu_742_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_774_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_79_fu_792_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_24_fu_796_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_81_fu_810_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_82_fu_822_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_83_fu_826_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t12_fu_832_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_80_fu_802_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t12_fu_840_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f12_fu_814_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_846_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_74_fu_864_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_22_fu_868_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_76_fu_882_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_77_fu_894_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_78_fu_898_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t11_fu_904_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_75_fu_874_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t11_fu_912_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f11_fu_886_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_918_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_69_fu_936_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_20_fu_940_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_71_fu_954_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_72_fu_966_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_73_fu_970_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t10_fu_976_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_70_fu_946_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t10_fu_984_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f10_fu_958_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_fu_990_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_64_fu_1008_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_18_fu_1012_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_66_fu_1026_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_67_fu_1038_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_68_fu_1042_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t8_fu_1048_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_65_fu_1018_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t9_fu_1056_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f9_fu_1030_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_1062_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_59_fu_1080_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_16_fu_1084_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_61_fu_1098_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_62_fu_1110_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_63_fu_1114_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t7_fu_1120_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_60_fu_1090_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t8_fu_1128_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f8_fu_1102_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_1134_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_54_fu_1152_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_14_fu_1156_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_56_fu_1170_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_57_fu_1182_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_58_fu_1186_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t6_fu_1192_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_55_fu_1162_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t7_fu_1200_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f6_fu_1174_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_1206_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_49_fu_1224_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_12_fu_1228_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_51_fu_1242_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_52_fu_1254_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_53_fu_1258_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t5_fu_1264_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_50_fu_1234_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t6_fu_1272_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f5_fu_1246_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_1278_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_44_fu_1296_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_10_fu_1300_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_46_fu_1314_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_47_fu_1326_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_48_fu_1330_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t3_fu_1336_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_45_fu_1306_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t4_fu_1344_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f4_fu_1318_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_1350_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_39_fu_1368_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_8_fu_1372_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_41_fu_1386_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_42_fu_1398_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_43_fu_1402_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t2_fu_1408_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_40_fu_1378_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t3_fu_1416_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f3_fu_1390_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_1422_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_34_fu_1440_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_6_fu_1444_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_36_fu_1458_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_37_fu_1470_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_38_fu_1474_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t1_fu_1480_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_35_fu_1450_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t2_fu_1488_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f1_fu_1462_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_1494_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_29_fu_1512_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_4_fu_1516_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_31_fu_1530_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_32_fu_1542_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_33_fu_1546_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t9_fu_1552_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_30_fu_1522_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t1_fu_1560_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f7_fu_1534_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_1566_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_1584_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_2_fu_1588_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_fu_1602_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_27_fu_1614_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_28_fu_1618_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t4_fu_1624_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_fu_1594_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t5_fu_1632_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f2_fu_1606_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_1638_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_1656_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_fu_1660_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_1674_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_22_fu_1686_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_1690_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_and_t_fu_1696_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_1666_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_neg_t_fu_1704_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_and_f_fu_1678_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_1710_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    align_reg_V_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            align_reg_V <= ap_const_lv32_0;
        elsif (ap_clk'event and ap_clk =  '1') then
            if ((((ap_const_lv5_0 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_3 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                align_reg_V <= data_word_sig_markerAlignment_V;
            end if; 
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            ap_CS_fsm <= ap_ST_fsm_state1;
        elsif (ap_clk'event and ap_clk =  '1') then
            ap_CS_fsm <= ap_NS_fsm;
        end if;
    end process;


    frame_pulse_notify_r_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            frame_pulse_notify_r <= ap_const_lv1_0;
        elsif (ap_clk'event and ap_clk =  '1') then
            if ((((ap_const_lv5_7 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_C = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_D = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_E = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_13 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_14 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_15 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_0 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_2 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_5 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_6 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                frame_pulse_notify_r <= ap_const_lv1_1;
            elsif ((((ap_const_lv5_8 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_9 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_A = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_F = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_10 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_11 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_16 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_17 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_18 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_1 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_B = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_12 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_19 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_1A = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_3 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_4 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                frame_pulse_notify_r <= ap_const_lv1_0;
            end if; 
        end if;
    end process;


    frame_pulse_sig_reg_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            frame_pulse_sig_reg <= ap_const_lv1_0;
        elsif (ap_clk'event and ap_clk =  '1') then
            if ((((ap_const_lv5_7 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_C = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_D = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_E = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_13 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_14 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_15 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_0 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_2 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_5 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_6 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                frame_pulse_sig_reg <= ap_const_lv1_1;
            end if; 
        end if;
    end process;


    frm_cnt_reg_V_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            frm_cnt_reg_V <= ap_const_lv32_3F;
        elsif (ap_clk'event and ap_clk =  '1') then
            if (((ap_const_lv5_2 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_1_fu_1718_p1;
            elsif ((((ap_const_lv5_0 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_3 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                frm_cnt_reg_V <= ap_const_lv32_0;
            elsif (((ap_const_lv5_4 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_3_fu_1646_p1;
            elsif (((ap_const_lv5_5 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_5_fu_1574_p1;
            elsif (((ap_const_lv5_6 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_7_fu_1502_p1;
            elsif (((ap_const_lv5_7 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_9_fu_1430_p1;
            elsif (((ap_const_lv5_8 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_11_fu_1358_p1;
            elsif (((ap_const_lv5_9 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_13_fu_1286_p1;
            elsif (((ap_const_lv5_A = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_15_fu_1214_p1;
            elsif (((ap_const_lv5_C = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_17_fu_1142_p1;
            elsif (((ap_const_lv5_D = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_19_fu_1070_p1;
            elsif (((ap_const_lv5_E = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_21_fu_998_p1;
            elsif (((ap_const_lv5_F = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_23_fu_926_p1;
            elsif (((ap_const_lv5_10 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_25_fu_854_p1;
            elsif (((ap_const_lv5_11 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_27_fu_782_p1;
            elsif (((ap_const_lv5_13 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_29_fu_710_p1;
            elsif (((ap_const_lv5_14 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_31_fu_638_p1;
            elsif (((ap_const_lv5_15 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_33_fu_566_p1;
            elsif (((ap_const_lv5_16 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_35_fu_494_p1;
            elsif (((ap_const_lv5_17 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_37_fu_422_p1;
            elsif (((ap_const_lv5_18 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                frm_cnt_reg_V <= r_V_39_fu_350_p1;
            end if; 
        end if;
    end process;


    nextphase_reg_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            nextphase_reg <= ap_const_lv3_3;
        elsif (ap_clk'event and ap_clk =  '1') then
            if ((((ap_const_lv5_0 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_3 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                nextphase_reg <= ap_const_lv3_0;
            elsif ((((ap_const_lv5_C = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_F = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                nextphase_reg <= ap_const_lv3_2;
            elsif ((((ap_const_lv5_8 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_13 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_16 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_5 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                nextphase_reg <= ap_const_lv3_3;
            elsif ((((ap_const_lv5_9 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_D = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_10 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_14 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_17 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_6 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                nextphase_reg <= ap_const_lv3_4;
            end if; 
        end if;
    end process;


    oof_sig_reg_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            oof_sig_reg <= ap_const_lv1_1;
        elsif (ap_clk'event and ap_clk =  '1') then
            if ((((ap_const_lv5_9 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_6 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                oof_sig_reg <= ap_const_lv1_0;
            elsif ((((ap_const_lv5_13 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_lv5_16 = active_operation_rea_read_fu_138_p2) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                oof_sig_reg <= ap_const_lv1_1;
            end if; 
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    active_operation_rea_read_fu_138_p2 <= active_operation;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    frame_pulse_notify <= frame_pulse_notify_r(0);
    frame_pulse_sig <= frame_pulse_sig_reg(0);
    oof_sig <= oof_sig_reg(0);
    out_align_V <= align_reg_V;
    out_frm_cnt_V <= frm_cnt_reg_V;
    out_nextphase <= nextphase_reg;
    p_and_f10_fu_958_p3 <= (ap_const_lv2_0 & tmp_71_fu_954_p1);
    p_and_f11_fu_886_p3 <= (ap_const_lv2_0 & tmp_76_fu_882_p1);
    p_and_f12_fu_814_p3 <= (ap_const_lv2_0 & tmp_81_fu_810_p1);
    p_and_f13_fu_742_p3 <= (ap_const_lv2_0 & tmp_86_fu_738_p1);
    p_and_f14_fu_670_p3 <= (ap_const_lv2_0 & tmp_91_fu_666_p1);
    p_and_f15_fu_598_p3 <= (ap_const_lv2_0 & tmp_96_fu_594_p1);
    p_and_f16_fu_526_p3 <= (ap_const_lv2_0 & tmp_101_fu_522_p1);
    p_and_f17_fu_454_p3 <= (ap_const_lv2_0 & tmp_106_fu_450_p1);
    p_and_f18_fu_382_p3 <= (ap_const_lv2_0 & tmp_111_fu_378_p1);
    p_and_f19_fu_310_p3 <= (ap_const_lv2_0 & tmp_116_fu_306_p1);
    p_and_f1_fu_1462_p3 <= (ap_const_lv2_0 & tmp_36_fu_1458_p1);
    p_and_f2_fu_1606_p3 <= (ap_const_lv2_0 & tmp_26_fu_1602_p1);
    p_and_f3_fu_1390_p3 <= (ap_const_lv2_0 & tmp_41_fu_1386_p1);
    p_and_f4_fu_1318_p3 <= (ap_const_lv2_0 & tmp_46_fu_1314_p1);
    p_and_f5_fu_1246_p3 <= (ap_const_lv2_0 & tmp_51_fu_1242_p1);
    p_and_f6_fu_1174_p3 <= (ap_const_lv2_0 & tmp_56_fu_1170_p1);
    p_and_f7_fu_1534_p3 <= (ap_const_lv2_0 & tmp_31_fu_1530_p1);
    p_and_f8_fu_1102_p3 <= (ap_const_lv2_0 & tmp_61_fu_1098_p1);
    p_and_f9_fu_1030_p3 <= (ap_const_lv2_0 & tmp_66_fu_1026_p1);
    p_and_f_fu_1678_p3 <= (ap_const_lv2_0 & tmp_21_fu_1674_p1);
    p_and_t10_fu_976_p3 <= (ap_const_lv2_0 & tmp_73_fu_970_p2);
    p_and_t11_fu_904_p3 <= (ap_const_lv2_0 & tmp_78_fu_898_p2);
    p_and_t12_fu_832_p3 <= (ap_const_lv2_0 & tmp_83_fu_826_p2);
    p_and_t13_fu_760_p3 <= (ap_const_lv2_0 & tmp_88_fu_754_p2);
    p_and_t14_fu_688_p3 <= (ap_const_lv2_0 & tmp_93_fu_682_p2);
    p_and_t15_fu_616_p3 <= (ap_const_lv2_0 & tmp_98_fu_610_p2);
    p_and_t16_fu_544_p3 <= (ap_const_lv2_0 & tmp_103_fu_538_p2);
    p_and_t17_fu_472_p3 <= (ap_const_lv2_0 & tmp_108_fu_466_p2);
    p_and_t18_fu_400_p3 <= (ap_const_lv2_0 & tmp_113_fu_394_p2);
    p_and_t19_fu_328_p3 <= (ap_const_lv2_0 & tmp_118_fu_322_p2);
    p_and_t1_fu_1480_p3 <= (ap_const_lv2_0 & tmp_38_fu_1474_p2);
    p_and_t2_fu_1408_p3 <= (ap_const_lv2_0 & tmp_43_fu_1402_p2);
    p_and_t3_fu_1336_p3 <= (ap_const_lv2_0 & tmp_48_fu_1330_p2);
    p_and_t4_fu_1624_p3 <= (ap_const_lv2_0 & tmp_28_fu_1618_p2);
    p_and_t5_fu_1264_p3 <= (ap_const_lv2_0 & tmp_53_fu_1258_p2);
    p_and_t6_fu_1192_p3 <= (ap_const_lv2_0 & tmp_58_fu_1186_p2);
    p_and_t7_fu_1120_p3 <= (ap_const_lv2_0 & tmp_63_fu_1114_p2);
    p_and_t8_fu_1048_p3 <= (ap_const_lv2_0 & tmp_68_fu_1042_p2);
    p_and_t9_fu_1552_p3 <= (ap_const_lv2_0 & tmp_33_fu_1546_p2);
    p_and_t_fu_1696_p3 <= (ap_const_lv2_0 & tmp_23_fu_1690_p2);
    p_neg_t10_fu_984_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t10_fu_976_p3));
    p_neg_t11_fu_912_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t11_fu_904_p3));
    p_neg_t12_fu_840_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t12_fu_832_p3));
    p_neg_t13_fu_768_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t13_fu_760_p3));
    p_neg_t14_fu_696_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t14_fu_688_p3));
    p_neg_t15_fu_624_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t15_fu_616_p3));
    p_neg_t16_fu_552_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t16_fu_544_p3));
    p_neg_t17_fu_480_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t17_fu_472_p3));
    p_neg_t18_fu_408_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t18_fu_400_p3));
    p_neg_t19_fu_336_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t19_fu_328_p3));
    p_neg_t1_fu_1560_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t9_fu_1552_p3));
    p_neg_t2_fu_1488_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t1_fu_1480_p3));
    p_neg_t3_fu_1416_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t2_fu_1408_p3));
    p_neg_t4_fu_1344_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t3_fu_1336_p3));
    p_neg_t5_fu_1632_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t4_fu_1624_p3));
    p_neg_t6_fu_1272_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t5_fu_1264_p3));
    p_neg_t7_fu_1200_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t6_fu_1192_p3));
    p_neg_t8_fu_1128_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t7_fu_1120_p3));
    p_neg_t9_fu_1056_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t8_fu_1048_p3));
    p_neg_t_fu_1704_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(p_and_t_fu_1696_p3));
    r_V_10_fu_1300_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_44_fu_1296_p1));
        r_V_11_fu_1358_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_1350_p3),32));

    r_V_12_fu_1228_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_49_fu_1224_p1));
        r_V_13_fu_1286_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_1278_p3),32));

    r_V_14_fu_1156_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_54_fu_1152_p1));
        r_V_15_fu_1214_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_fu_1206_p3),32));

    r_V_16_fu_1084_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_59_fu_1080_p1));
        r_V_17_fu_1142_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_fu_1134_p3),32));

    r_V_18_fu_1012_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_64_fu_1008_p1));
        r_V_19_fu_1070_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_1062_p3),32));

        r_V_1_fu_1718_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_1710_p3),32));

    r_V_20_fu_940_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_69_fu_936_p1));
        r_V_21_fu_998_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_990_p3),32));

    r_V_22_fu_868_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_74_fu_864_p1));
        r_V_23_fu_926_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_11_fu_918_p3),32));

    r_V_24_fu_796_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_79_fu_792_p1));
        r_V_25_fu_854_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_12_fu_846_p3),32));

    r_V_26_fu_724_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_84_fu_720_p1));
        r_V_27_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_13_fu_774_p3),32));

    r_V_28_fu_652_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_89_fu_648_p1));
        r_V_29_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_14_fu_702_p3),32));

    r_V_2_fu_1588_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_24_fu_1584_p1));
    r_V_30_fu_580_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_94_fu_576_p1));
        r_V_31_fu_638_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_15_fu_630_p3),32));

    r_V_32_fu_508_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_99_fu_504_p1));
        r_V_33_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_fu_558_p3),32));

    r_V_34_fu_436_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_104_fu_432_p1));
        r_V_35_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_486_p3),32));

    r_V_36_fu_364_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_109_fu_360_p1));
        r_V_37_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_414_p3),32));

    r_V_38_fu_292_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_114_fu_288_p1));
        r_V_39_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_19_fu_342_p3),32));

        r_V_3_fu_1646_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_1638_p3),32));

    r_V_4_fu_1516_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_29_fu_1512_p1));
        r_V_5_fu_1574_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_1566_p3),32));

    r_V_6_fu_1444_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_34_fu_1440_p1));
        r_V_7_fu_1502_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_1494_p3),32));

    r_V_8_fu_1372_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_39_fu_1368_p1));
        r_V_9_fu_1430_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_1422_p3),32));

    r_V_fu_1660_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(tmp_fu_1656_p1));
    tmp_100_fu_514_p3 <= r_V_32_fu_508_p2(7 downto 7);
    tmp_101_fu_522_p1 <= r_V_32_fu_508_p2(6 - 1 downto 0);
    tmp_102_fu_534_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_103_fu_538_p2 <= (tmp_102_fu_534_p1 xor ap_const_lv6_3F);
    tmp_104_fu_432_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_105_fu_442_p3 <= r_V_34_fu_436_p2(7 downto 7);
    tmp_106_fu_450_p1 <= r_V_34_fu_436_p2(6 - 1 downto 0);
    tmp_107_fu_462_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_108_fu_466_p2 <= (tmp_107_fu_462_p1 xor ap_const_lv6_3F);
    tmp_109_fu_360_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_10_fu_990_p3 <= 
        p_neg_t10_fu_984_p2 when (tmp_70_fu_946_p3(0) = '1') else 
        p_and_f10_fu_958_p3;
    tmp_110_fu_370_p3 <= r_V_36_fu_364_p2(7 downto 7);
    tmp_111_fu_378_p1 <= r_V_36_fu_364_p2(6 - 1 downto 0);
    tmp_112_fu_390_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_113_fu_394_p2 <= (tmp_112_fu_390_p1 xor ap_const_lv6_3F);
    tmp_114_fu_288_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_115_fu_298_p3 <= r_V_38_fu_292_p2(7 downto 7);
    tmp_116_fu_306_p1 <= r_V_38_fu_292_p2(6 - 1 downto 0);
    tmp_117_fu_318_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_118_fu_322_p2 <= (tmp_117_fu_318_p1 xor ap_const_lv6_3F);
    tmp_11_fu_918_p3 <= 
        p_neg_t11_fu_912_p2 when (tmp_75_fu_874_p3(0) = '1') else 
        p_and_f11_fu_886_p3;
    tmp_12_fu_846_p3 <= 
        p_neg_t12_fu_840_p2 when (tmp_80_fu_802_p3(0) = '1') else 
        p_and_f12_fu_814_p3;
    tmp_13_fu_774_p3 <= 
        p_neg_t13_fu_768_p2 when (tmp_85_fu_730_p3(0) = '1') else 
        p_and_f13_fu_742_p3;
    tmp_14_fu_702_p3 <= 
        p_neg_t14_fu_696_p2 when (tmp_90_fu_658_p3(0) = '1') else 
        p_and_f14_fu_670_p3;
    tmp_15_fu_630_p3 <= 
        p_neg_t15_fu_624_p2 when (tmp_95_fu_586_p3(0) = '1') else 
        p_and_f15_fu_598_p3;
    tmp_16_fu_558_p3 <= 
        p_neg_t16_fu_552_p2 when (tmp_100_fu_514_p3(0) = '1') else 
        p_and_f16_fu_526_p3;
    tmp_17_fu_486_p3 <= 
        p_neg_t17_fu_480_p2 when (tmp_105_fu_442_p3(0) = '1') else 
        p_and_f17_fu_454_p3;
    tmp_18_fu_414_p3 <= 
        p_neg_t18_fu_408_p2 when (tmp_110_fu_370_p3(0) = '1') else 
        p_and_f18_fu_382_p3;
    tmp_19_fu_342_p3 <= 
        p_neg_t19_fu_336_p2 when (tmp_115_fu_298_p3(0) = '1') else 
        p_and_f19_fu_310_p3;
    tmp_1_fu_1566_p3 <= 
        p_neg_t1_fu_1560_p2 when (tmp_30_fu_1522_p3(0) = '1') else 
        p_and_f7_fu_1534_p3;
    tmp_20_fu_1666_p3 <= r_V_fu_1660_p2(7 downto 7);
    tmp_21_fu_1674_p1 <= r_V_fu_1660_p2(6 - 1 downto 0);
    tmp_22_fu_1686_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_23_fu_1690_p2 <= (tmp_22_fu_1686_p1 xor ap_const_lv6_3F);
    tmp_24_fu_1584_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_25_fu_1594_p3 <= r_V_2_fu_1588_p2(7 downto 7);
    tmp_26_fu_1602_p1 <= r_V_2_fu_1588_p2(6 - 1 downto 0);
    tmp_27_fu_1614_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_28_fu_1618_p2 <= (tmp_27_fu_1614_p1 xor ap_const_lv6_3F);
    tmp_29_fu_1512_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_2_fu_1494_p3 <= 
        p_neg_t2_fu_1488_p2 when (tmp_35_fu_1450_p3(0) = '1') else 
        p_and_f1_fu_1462_p3;
    tmp_30_fu_1522_p3 <= r_V_4_fu_1516_p2(7 downto 7);
    tmp_31_fu_1530_p1 <= r_V_4_fu_1516_p2(6 - 1 downto 0);
    tmp_32_fu_1542_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_33_fu_1546_p2 <= (tmp_32_fu_1542_p1 xor ap_const_lv6_3F);
    tmp_34_fu_1440_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_35_fu_1450_p3 <= r_V_6_fu_1444_p2(7 downto 7);
    tmp_36_fu_1458_p1 <= r_V_6_fu_1444_p2(6 - 1 downto 0);
    tmp_37_fu_1470_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_38_fu_1474_p2 <= (tmp_37_fu_1470_p1 xor ap_const_lv6_3F);
    tmp_39_fu_1368_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_3_fu_1422_p3 <= 
        p_neg_t3_fu_1416_p2 when (tmp_40_fu_1378_p3(0) = '1') else 
        p_and_f3_fu_1390_p3;
    tmp_40_fu_1378_p3 <= r_V_8_fu_1372_p2(7 downto 7);
    tmp_41_fu_1386_p1 <= r_V_8_fu_1372_p2(6 - 1 downto 0);
    tmp_42_fu_1398_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_43_fu_1402_p2 <= (tmp_42_fu_1398_p1 xor ap_const_lv6_3F);
    tmp_44_fu_1296_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_45_fu_1306_p3 <= r_V_10_fu_1300_p2(7 downto 7);
    tmp_46_fu_1314_p1 <= r_V_10_fu_1300_p2(6 - 1 downto 0);
    tmp_47_fu_1326_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_48_fu_1330_p2 <= (tmp_47_fu_1326_p1 xor ap_const_lv6_3F);
    tmp_49_fu_1224_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_4_fu_1062_p3 <= 
        p_neg_t9_fu_1056_p2 when (tmp_65_fu_1018_p3(0) = '1') else 
        p_and_f9_fu_1030_p3;
    tmp_50_fu_1234_p3 <= r_V_12_fu_1228_p2(7 downto 7);
    tmp_51_fu_1242_p1 <= r_V_12_fu_1228_p2(6 - 1 downto 0);
    tmp_52_fu_1254_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_53_fu_1258_p2 <= (tmp_52_fu_1254_p1 xor ap_const_lv6_3F);
    tmp_54_fu_1152_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_55_fu_1162_p3 <= r_V_14_fu_1156_p2(7 downto 7);
    tmp_56_fu_1170_p1 <= r_V_14_fu_1156_p2(6 - 1 downto 0);
    tmp_57_fu_1182_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_58_fu_1186_p2 <= (tmp_57_fu_1182_p1 xor ap_const_lv6_3F);
    tmp_59_fu_1080_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_5_fu_1350_p3 <= 
        p_neg_t4_fu_1344_p2 when (tmp_45_fu_1306_p3(0) = '1') else 
        p_and_f4_fu_1318_p3;
    tmp_60_fu_1090_p3 <= r_V_16_fu_1084_p2(7 downto 7);
    tmp_61_fu_1098_p1 <= r_V_16_fu_1084_p2(6 - 1 downto 0);
    tmp_62_fu_1110_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_63_fu_1114_p2 <= (tmp_62_fu_1110_p1 xor ap_const_lv6_3F);
    tmp_64_fu_1008_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_65_fu_1018_p3 <= r_V_18_fu_1012_p2(7 downto 7);
    tmp_66_fu_1026_p1 <= r_V_18_fu_1012_p2(6 - 1 downto 0);
    tmp_67_fu_1038_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_68_fu_1042_p2 <= (tmp_67_fu_1038_p1 xor ap_const_lv6_3F);
    tmp_69_fu_936_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_6_fu_1278_p3 <= 
        p_neg_t6_fu_1272_p2 when (tmp_50_fu_1234_p3(0) = '1') else 
        p_and_f5_fu_1246_p3;
    tmp_70_fu_946_p3 <= r_V_20_fu_940_p2(7 downto 7);
    tmp_71_fu_954_p1 <= r_V_20_fu_940_p2(6 - 1 downto 0);
    tmp_72_fu_966_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_73_fu_970_p2 <= (tmp_72_fu_966_p1 xor ap_const_lv6_3F);
    tmp_74_fu_864_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_75_fu_874_p3 <= r_V_22_fu_868_p2(7 downto 7);
    tmp_76_fu_882_p1 <= r_V_22_fu_868_p2(6 - 1 downto 0);
    tmp_77_fu_894_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_78_fu_898_p2 <= (tmp_77_fu_894_p1 xor ap_const_lv6_3F);
    tmp_79_fu_792_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_7_fu_1710_p3 <= 
        p_neg_t_fu_1704_p2 when (tmp_20_fu_1666_p3(0) = '1') else 
        p_and_f_fu_1678_p3;
    tmp_80_fu_802_p3 <= r_V_24_fu_796_p2(7 downto 7);
    tmp_81_fu_810_p1 <= r_V_24_fu_796_p2(6 - 1 downto 0);
    tmp_82_fu_822_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_83_fu_826_p2 <= (tmp_82_fu_822_p1 xor ap_const_lv6_3F);
    tmp_84_fu_720_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_85_fu_730_p3 <= r_V_26_fu_724_p2(7 downto 7);
    tmp_86_fu_738_p1 <= r_V_26_fu_724_p2(6 - 1 downto 0);
    tmp_87_fu_750_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_88_fu_754_p2 <= (tmp_87_fu_750_p1 xor ap_const_lv6_3F);
    tmp_89_fu_648_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_8_fu_1206_p3 <= 
        p_neg_t7_fu_1200_p2 when (tmp_55_fu_1162_p3(0) = '1') else 
        p_and_f6_fu_1174_p3;
    tmp_90_fu_658_p3 <= r_V_28_fu_652_p2(7 downto 7);
    tmp_91_fu_666_p1 <= r_V_28_fu_652_p2(6 - 1 downto 0);
    tmp_92_fu_678_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_93_fu_682_p2 <= (tmp_92_fu_678_p1 xor ap_const_lv6_3F);
    tmp_94_fu_576_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_95_fu_586_p3 <= r_V_30_fu_580_p2(7 downto 7);
    tmp_96_fu_594_p1 <= r_V_30_fu_580_p2(6 - 1 downto 0);
    tmp_97_fu_606_p1 <= frm_cnt_reg_V(6 - 1 downto 0);
    tmp_98_fu_610_p2 <= (tmp_97_fu_606_p1 xor ap_const_lv6_3F);
    tmp_99_fu_504_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_9_fu_1134_p3 <= 
        p_neg_t8_fu_1128_p2 when (tmp_60_fu_1090_p3(0) = '1') else 
        p_and_f8_fu_1102_p3;
    tmp_fu_1656_p1 <= frm_cnt_reg_V(8 - 1 downto 0);
    tmp_s_fu_1638_p3 <= 
        p_neg_t5_fu_1632_p2 when (tmp_25_fu_1594_p3(0) = '1') else 
        p_and_f2_fu_1606_p3;
end behav;
