-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity update_data is
port (
    ap_ready : OUT STD_LOGIC;
    data_V : IN STD_LOGIC_VECTOR (31 downto 0);
    data_count_V : IN STD_LOGIC_VECTOR (3 downto 0);
    rx_bit : IN STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of update_data is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal data_count_V_cast_fu_42_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_V_fu_46_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_56_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_66_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_1_fu_60_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_op_assign_cast_fu_52_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rhs_V_1_fu_84_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal agg_result_V_fu_96_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_76_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_1_fu_90_p2 : STD_LOGIC_VECTOR (31 downto 0);


begin



    agg_result_V_fu_96_p0 <= (0=>rx_bit, others=>'-');
    ap_ready <= ap_const_logic_1;
    ap_return <= 
        r_V_fu_76_p3 when (agg_result_V_fu_96_p0(0) = '1') else 
        r_V_1_fu_90_p2;
    data_count_V_cast_fu_42_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_count_V),8));
    i_op_assign_cast_fu_52_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rhs_V_fu_46_p2),32));
    r_V_1_fu_90_p2 <= (rhs_V_1_fu_84_p2 and data_V);
    r_V_fu_76_p3 <= (tmp_2_fu_66_p4 & tmp_1_fu_60_p2);
    rhs_V_1_fu_84_p2 <= (i_op_assign_cast_fu_52_p1 xor ap_const_lv32_FFFFFFFF);
    rhs_V_fu_46_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv8_1),to_integer(unsigned('0' & data_count_V_cast_fu_42_p1(8-1 downto 0)))));
    tmp_1_fu_60_p2 <= (tmp_fu_56_p1 or rhs_V_fu_46_p2);
    tmp_2_fu_66_p4 <= data_V(31 downto 8);
    tmp_fu_56_p1 <= data_V(8 - 1 downto 0);
end behav;
